// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
)

type Sale struct {
	ID          string         `json:"id"`
	TicketID    string         `json:"ticket_id"`
	UserID      string         `json:"user_id"`
	PaymentType sql.NullString `json:"payment_type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Ticket struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"`
	Price    float64 `json:"price"`
	Quantity int32   `json:"quantity"`
}
