// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"context"
)

type Querier interface {
	CreateSale(ctx context.Context, arg CreateSaleParams) error
	GetAllTickets(ctx context.Context) ([]Ticket, error)
	GetSaleByID(ctx context.Context, id string) (Sale, error)
	GetTicketByID(ctx context.Context, id string) (Ticket, error)
	UpdateTicketQuantity(ctx context.Context, arg UpdateTicketQuantityParams) error
}

var _ Querier = (*Queries)(nil)
