services:
  mysql_db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=daniel
      - MYSQL_PASSWORD=daniel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  tickets-api:
    build: ./tickets-api
    container_name: tickets-api
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
      - redis

