version: '3.5'

services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        networks:
            - default-services
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=auth_db
          - MYSQL_USER=auth
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3306:3306"

    mailcatcher:
      container_name: mailcatcher
      image: schickling/mailcatcher
      ports:
          - 1080:1080
          - 1025:1025
      networks:
          - default-services

    rabbitmq:
        image: rabbitmq:3.7-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_USER: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - default-services
networks:
    default-services:
