version: '3.5'

services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        networks:
            - default-services
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - MYSQL_DATABASE=tickets_db
          - MYSQL_USER=tickets_user
          - MYSQL_PASSWORD=tickets_passwd
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3306:3306"

networks:
    default-services: